### ISSUE TITLE
Application - Détails événement - Mettre des labels devant les informations

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-app#10]
Au sein de l'écran du détail de l'événement :
<Titre>
Lieu : <`lieu`>
Date et heure de Début : <`date/heure début`, format : `DD mois à HH\hii`)
Date et heure de fin: <`date/heure fin`, format : `DD mois à HH\hii`)
Commentaire :
<`commentaire`>

**Comment by cchampou** [comment]
1.7.1

**Comment by cmoysan** [comment]
**Ok pour moi.**
