### ISSUE TITLE
Application - Lorsqu'il n'y a pas de lien eprotec de renseigné, ne pas afficher le bouton Eprotec

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-app#11]
Dans le détail de l'événement, 
En dessous des bouton Dispo / No dispo, mettre en place la règle métier suivante concernant le bouton Lien eprotec : Afficher le bouton, uniquement si un lien Eprotec est renseigné au sein de l'événement.

**Comment by cchampou** [comment]
1.7.4, déploiement en cours

**Comment by cmoysan** [comment]
**Ok pour moi.**
