### ISSUE TITLE
[MOBILE] Afficher ma réponse au sein du déclenchement

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-app#3]
En tant que secouriste
Je souhaite voir un écran différent lorsque j'ai apporté ma réponse
Afin de m'indiquer que tout c'est bien passé.

--

## Règles métiers
1. Au tap/clic sur le bouton Dispo ou non Dispo alors il faut afficher l'information comme quoi tout c'est bien passé (ou non) :
   - Si le secouriste indique qu'il est dispo, afficher le message suivant : `Nous avons bien enregistrés votre disponibilité`. Ne plus afficher les boutons, à la place afficher la réponse : `Je suis disponible - Modifier ?`
   - Si le secouriste indique qu'il n'est pas dispo, afficher le message suivant : `Nous avons bien enregistrés votre indisponibilité`. Ne plus afficher les boutons, à la place afficher la réponse : `Je suis indisponible - Modifier ?`
   - Si erreur avec API, alors afficher le message suivant : `Impossible d'enregistrer, veuillez recommencer.`
2. Pouvoir modifier sa réponse : Au tap/clic sur `Modifier ?`, alors : 
   - afficher de nouveau les boutons.
   - Ajouter un CTA supplémentaire : Annuler (style lien). Au tap/clic, cacher les boutons et réafficher la réponse sans modification.
3. Au sein de la liste des déclenchements, afficher le statut en fonction de la réponse :
   - ✅ Dispo (Si le secouriste a répondu Dispo)
   - ❌ Indispo (Si le secouriste a répondu Indispo)
   - ⏳ Non répondu (Si le secouriste n'a pas apporté de réponse)

**Comment by cmoysan** [comment]
@cchampou au niveau de la liste des déclenchements. En plus des emoticones est-ce qu'il est possible de mettre le terme Dispo/Indispo/Non répondu. JE pinaille, mais je le verrais bien en haut à droite de l'encart.

**Comment by cchampou** [comment]
@cmoysan c'est fait ✅

**Comment by cmoysan** [comment]
@cchampou je peux pinailler encore ? 
Est-ce qu'on peut mettre à la fin du bloc, la réponse qu'un secouriste a apporté pour l'événement.
Exemple :
Festival de musique
Transbordeur - 03/02/2023 17:00
--
**⏳ Non répondu**

**Comment by cchampou** [comment]
C'est corrigé ✅

**Comment by cmoysan** [comment]
**Ok pour moi.**
