### ISSUE TITLE
EVENEMENT - Améliorer l'affichage des événements au sein de l'application

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-app#4]
Au sein de l'écran listant les événements il faut améliorer l'affichage :

1. Faire deux parties : Evénements en cours et Historique
2. Dans Evenements en cours mettre les événements qui ont une date de fin supérieure à la date du jour.
3. Dans Evenements en cours : classer les événéments de la sorte : 
- En premier avoir les événements dont on attend la réponse du secouriste.
- Ensuite avoir les autres événements dont la réponse a été renseignée et dans l'ordre suivant : Date de début au plus proche de la date du jour.
5. Dans Historique mettre les événements qui ont une date de fin antérieur à la date du jour.

TODO : Fournir un design d'écran

**Comment by cmoysan** [comment]
**Ok pour moi.**
