### ISSUE TITLE
EVENEMENT - Au sein de l'application, dans le détail d'un événement, pouvoir scroller permettant d'indiquer sa dispo ou non

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-app#5]
Dès que j'ai un commentaire, assez long, le secouriste n'a pas la possibilité de renseigner sa dispo parce que le commentaire est long. 

Mettre en place le Scroll, permettant au secouriste d'accéder aux boutons dispo / non dispo.

**Comment by cmoysan** [comment]
**Ok pour moi.**
