### ISSUE TITLE
Avoir l'information comme quoi le secouriste a consulté l'événément

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-app#6]
- Mettre en place le statut seen.
- Au sein de l'administration : faire évoluer l'affichage au sein de la colonne Disponibilté, dans le détail de l'événement => 
1. Non consulté (Par défaut) => Statut seen, le secouriste n'a pas encore consulté l'événement. Statut par défaut à la création.
2. Consulté, en attente de réponse => le secouriste a consulté au sein de l'appli l'événement, mais n'a pas indiqué s'il était disponible.
3. Disponible => Au clic sur le bouton Disponible.
4. Non disponible => Au clic sur le bouton Non Disponible.
- Au sein de l'app :
  - Dans la liste des événements, ne rien afficher comme texte au sein de chaque bloc. Faire ressortir le bloc non consulté, en mettant en surbrillance le bloc.
  - Au sein de l'écran de l'événement, n'afficher aucune information, faire en sorte d'afficher le texte et les boutons Disponible / non disponible.

**Comment by cmoysan** [comment]
**Ok pour moi.**
