### ISSUE TITLE
mobile - Souci d'affichage dans la liste des événéments

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-app#7]
En tant que secouriste
Je souhaite avoir une liste qui affiche uniquement les événement (et non des cadres blancs)
Afin de me permettre d'avoir une application aux petits oignons

![Image](https://user-images.githubusercontent.com/1431054/216813170-fa641171-95e6-4a93-90db-28888b9cda2e.png)

**Comment by cchampou** [comment]
Corrigé dans la 1.6.0

**Comment by cmoysan** [comment]
**Test ok.**
